### ISSUE TITLE
TEI Github adapter

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/catalogue-pipeline#1536]

**Comment by alicefuzier** [comment]
- [ ] RFC. (https://github.com/wellcomecollection/docs/pull/57)
- [ ] TEI Windows Lambda (PR https://github.com/wellcomecollection/catalogue-pipeline/pull/1586)
- [ ] TEI GitHub Adapter Service
- [ ] TEI Adapter Service
