### ISSUE TITLE
Deal with IDs in 524 and 001

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/catalogue-pipeline#1548]
IDs are often stored in the `524` / `001` fields in Sierra.

`524` is often stored as `Wellcome Library no. 1819i`

`001` is often just the i number `1819i`

When searching for these - they are treated as free text, so have fuzziness and other things applied, which makes them hard to find. An example is https://api.wellcomecollection.org/catalogue/v2/works/?query=1819i where [the expected result](https://wellcomecollection.org/works/vpjz5a7d) is literally the last on the list.

We should think how we want this to be filterable e.g. similar to the `identifiers` filter.

Potential solutions:
* Add to something similar to shelf mark
* Extract this ID and storing it in the `otherIdentifiers` field, similar to [`digcodes`](https://api.wellcomecollection.org/catalogue/v2/works/vj3bap7x?include=identifiers,notes)

**Comment by alexwlchan** [comment]
For the Visual Collections, we're now extracting 001 as an identifier and reference number: https://github.com/wellcomecollection/platform/issues/5172
