### ISSUE TITLE
map TEI transliterated titles into the alternativeTitles field

### ISSUE THREAD

**Issue by harrisonpim** [wellcomecollection/catalogue-pipeline#2043]
TEI transliterated titles should be mapped into alternativeTitles ([see here](https://github.com/wellcomecollection/catalogue-pipeline/blob/main/pipeline/transformer/transformer_tei/src/main/scala/weco/pipeline/transformer/tei/TeiData.scala#L122))

**Comment by paul-butcher** [comment]
Does this mean to extract the title from this line: 
<title xml:lang="ar-Latn-x-lc" type="standard" key="work_3001">Al-Qānūn fī al-ṭibb</title>

https://github.com/wellcomecollection/wellcome-collection-tei/blob/d284be20c9ca9b88da21895847edd9da0216686a/Arabic/WMS_Arabic_1.xml#L45

Would that be any title that is not of type="original"?

**Comment by harrisonpim** [comment]
That sounds right to me. Sorry for not leaving more context on this issue!
