### ISSUE TITLE
Re-ingest L0024908 into DLCS

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/catalogue-pipeline#2144]
For some reason it got deleted in DLCS, so the image inferrer can't find it.

We should reingest it, and document the procedure if it isn't already.

**Comment by jcateswellcome** [comment]
@kenoir or @pollecuttn any ideas on this one? Just doing a minor tidy up and closing mostly recent issues but this one caught my eye.

**Comment by pollecuttn** [comment]
Guessing that's not yet been re-ingested:
https://wellcomecollection.org/search/works?query=L0024908

**Comment by kenoir** [comment]
Probably worth working through, even if just to understand it a bit more.
