### ISSUE TITLE
Add an exclusion for other folders in the TEI repo

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/catalogue-pipeline#2197]
@adrianplau has asked us to add exclusions for other directories in the TEI repo; files we shouldn't transform and present in the front-end.

This is a small change to the TEI ID extractor; we already exclude files from the "Templates" directory: https://github.com/wellcomecollection/catalogue-pipeline/blob/e650e334d9735ae3b62ecddaf9e6efb16a35e89c/tei_adapter/tei_id_extractor/src/main/scala/weco/catalogue/tei/id_extractor/TeiIdExtractorWorkerService.scala#L108-L114

We're waiting for him to give us the list of folders.

**Comment by adrianplau** [comment]
Thanks for this, Alex! The folder is this one: https://github.com/wellcomecollection/wellcome-collection-tei/tree/main/Arabic/Fihrist

By the way, I assume the [docs](https://github.com/wellcomecollection/wellcome-collection-tei/tree/main/docs) folder also is excluded?

**Comment by alexwlchan** [comment]
Done.
