### ISSUE TITLE
replace LSH image similarity with native elasticsearch knn search

### ISSUE THREAD

**Issue by harrisonpim** [wellcomecollection/catalogue-pipeline#2236]

**Comment by alexwlchan** [comment]
See also: https://github.com/wellcomecollection/catalogue-pipeline/pull/2248

**Comment by paul-butcher** [comment]
@harrisonpim 

I've worked around the index creation problem by using `MappingDefinition(rawSource...)`. However, once rawSource is used, elastic4s silently ignores any further modifications to the mapping, so `MappingDefinition(rawSource...).dynamic(DynamicMapping.Strict)` does not result in a mapping with `dynamic` set to `strict`.

I'll have to do a bit more fiddling with this to make it work properly, but the index is now being created with the correct property mappings.

When running the test "indexes an image with large image features vectors", I get an error response saying "The [dot_product] similarity can only be used with unit-length vectors.", which is not relevant to the index creation part, so I'm kicking that back over the wall to you.

**Comment by harrisonpim** [comment]
✨ Brilliant, thanks!  
I'll have a go at normalising those test vectors to unit length - shouldn't be a significant hurdle afaict

**Comment by paul-butcher** [comment]
The property that was called `metric` in the branch before I made these changes looks like it should be called `similarity` https://www.elastic.co/guide/en/elasticsearch/reference/master/dense-vector.html#dense-vector-params

**Comment by harrisonpim** [comment]
good point!

**Comment by harrisonpim** [comment]
😖 ah, how annoying! well spotted though

**Comment by harrisonpim** [comment]
yes! new queries won't work without the new indexed data, and old queries will fail if they can't look at the old fields

**Comment by paul-butcher** [comment]
That's cool.  Since https://github.com/wellcomecollection/catalogue-pipeline/pull/2252 we have a new way to do that, which reminds me I should write a little howto about it.

Basically, buildkite in the catalogue pipeline now deploys onto the latest pipeline in terraform.  So we can add a new pipeline to this PR and it won't deploy to production until we switch production to point to that same pipeline.
