### ISSUE TITLE
Investigate removing the 'refresh_interval=0' behaviour from reindexes

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/catalogue-pipeline#2238]
Quoting [the Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-refresh-interval-setting):

> <dl><dt><code> index.refresh_interval</code></dt><dd>How often to perform a refresh operation, which makes recent changes to the index visible to search. Defaults to 1s. Can be set to -1 to disable refresh.</dd></dl>

We run the catalogue pipeline with two different values:

* when reindexing, `index.refresh_interval = -1`
* when running day-to-day, `index.refresh_interval = 1s`

This was originally added as a performance optimisation to reduce pressure on the Elasticsearch cluster, when we had a single cluster that was used for all API indexes.

It’s been a persistent source of confusion, because people see "works-indexed = 0 documents" and think something is broken.

We should investigate whether we can remove it – both the code and the confusion.

**Comment by alexwlchan** [comment]
I ran the https://github.com/wellcomecollection/catalogue-pipeline/pull/2237 pipeline (2022-11-03) with `index.refresh_interval = 1s` in the works index, and it was absolutely fine.

I didn't try it in the images index because I forgot to update the value; we should do that on the next reindex.

**Comment by jamieparkinson** [comment]
I would be in favour

**Comment by alexwlchan** [comment]
When we do the next reindex, let's run both works and images with `index.refresh_interval = 1s` and see what happens. If that's also okay, we can delete all this code.

**Comment by alexwlchan** [comment]
Paul has confirmed that this setting is no longer necessary in reindexes, so we should remove all the associated code: https://github.com/wellcomecollection/catalogue-pipeline/pull/2260

**Comment by alexwlchan** [comment]
Closing as done.
