### ISSUE TITLE
There are lots of Iliads by Homer

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/catalogue-pipeline#2308]
In https://wellcomecollection.org/works/deru75mu, there are nine different Subjects bearing the label "Homer. Iliad"
<img width="1288" alt="Screenshot 2023-01-24 at 16 52 53" src="https://user-images.githubusercontent.com/64621/214356755-7fa19397-af43-47ca-866c-7a3cb3732cc9.png">

They all bear different LCNames identifiers.

If we examine the fragment of Sierra JSON corresponding to one of them, we see that there is a subfield $l which appears to be being ignored during transformation.

```
{
          "fieldTag": "d",
          "marcTag": "600",
          "ind1": "0",
          "ind2": "0",
          "subfields": [
            {
              "tag": "a",
              "content": "Homer."
            },
            {
              "tag": "t",
              "content": "Iliad."
            },
            {
              "tag": "l",
              "content": "Slovak"
            },
            {
              "tag": "0",
              "content": "no 98129936"
            }
          ]
        }
```

https://id.loc.gov/authorities/names/no98129936.html is indeed the identifier for the Slovak version of the Iliad.  So it looks like we need to include this as part of the Concept label.

**Comment by paul-butcher** [comment]
This relates to https://github.com/wellcomecollection/catalogue-pipeline/issues/2302. I discovered that there are 1459 labels with more than one LCNames identifier associated with it in catalogue-concepts.  Originally thinking this was about authors vs works by the author, I was struck by the fact that "Homer. Iliad." was one such label.

**Comment by paul-butcher** [comment]
Notably, the root cause of this is not the same, or even similar to that seen in Freud's Totem und Tabu, which genuinely looks like a problem in the source data.

```
"varFields": [
        {
          "fieldTag": "a",
          "marcTag": "100",
          "ind1": "1",
          "ind2": " ",
          "subfields": [
            {
              "tag": "a",
              "content": "Freud, Sigmund,"
            },
            {
              "tag": "d",
              "content": "1856-1939"
            },
            {
              "tag": "0",
              "content": "n  91074218 "
            },
            {
              "tag": "0",
              "content": "n  91074218"
            }
          ]
        },
```

**Comment by pollecuttn** [comment]
We displayed the `$l`s on the previous catalogue:
![image](https://user-images.githubusercontent.com/1446072/214318394-5ed33609-9cee-4dc0-9f00-29188be51ac4.png)

https://catalogue.wellcomelibrary.org/record=b1306034

**Comment by pollecuttn** [comment]
I've ordered it up to have a look! But computer says it won't be here until Thursday so I'll have to check next Tuesday when I'm on site.

**Comment by pollecuttn** [comment]
The 008 says eng(lish) so I'm wondering if all those 600s are not right.
https://catalogue.wellcomelibrary.org/search~S8?/.b1306034/.b1306034/1%2C1%2C1%2CB/marc~b1306034

**Comment by paul-butcher** [comment]
We've just had a look at the book in question.  There is one mention of Homer in the index, pointing to page 176 (Homer's Hymn to Neptune (Neptune?  Homer was Greek)).  There is no mention of Iliad, either on its own or in connection with Homer.  Certainly no mention of diverse translations and renditions of that epic poem.

**Comment by paul-butcher** [comment]
However, the correctness or otherwise of the record does not detract from a need to transform the `$l` subfield

**Comment by paul-butcher** [comment]
This raises questions about compound concepts and their constituents, in particular, the degree to which we can treat a compound concept as a bag of tags.

In the case of all these Iliads, the `$l` and `$s` subfields are all subordinate to the `$t` field and meaningless on their own. e.g. in no2012111076:

```
"subfields": [
        {
          "tag": "a",
          "content": "Homer."
        },
        {
          "tag": "t",
          "content": "Iliad."
        },
        {
          "tag": "l",
          "content": "Greek."
        },
        {
          "tag": "s",
          "content": "(Mazon, Chantraine, Collart and Langumier)"
        },
        {
          "tag": "0",
          "content": "no2012111076"
        }
      ]
    },
```

This is the version of the Iliad in Greek recorded and published by those four scholars.  

To what extent is the Greekness relevant in its own right?  Would users wish to find all Works in any language that are about the Greek editions of any texts?  Importantly, this will probably only apply to texts that exist in multiple languages, because those in a single language will not be marked with `$l`.  Similarly, is `(Mazon, Chantraine, Collart and Langumier)` really a thing, in the absence of Iliad?

**Comment by paul-butcher** [comment]
Notably, in the LoC records, e.g. https://id.loc.gov/authorities/names/no2012111076.html the name of the "work" component is `Iliad, Greek`

**Comment by paul-butcher** [comment]
Also notable, the list of names comes under "Other Characteristic", rather than components.

**Comment by paul-butcher** [comment]
I think this might mean that these subfields should only contribute to the full name of the whole concept, but not create Concepts of their own in the concepts list

**Comment by paul-butcher** [comment]
When constructing a label for a Person, the Sierra transformer filters so that it only contains text from these subfields:

List("a", "b", "c", "d", "t", "p", "n", "q")

I understand that there are some subfields that we do not wish to include (0 being the most obvious one), but is this the correct way to do it?  Should we exclude the ones we don't want, instead of include the ones we do?

**Comment by paul-butcher** [comment]
Actually, listing what we want is correct.  The data coming in is not validated.  e.g. the $D subfield (should be $d in this example)

```
varField.marcTag600varField.subfields.tag[a, D]parent.id1566968parent.idWithCheckDigitb15669683parent.recordTypebibsposition4varField.fieldTagdvarField.ind11varField.ind20varField.subfields.content[Maimonides, Moses,, 1135-1204]_idbibs-1566968-4_indexsierra_varfields_score0
```

**Comment by paul-butcher** [comment]
$l definitely forms part of the name of the whole.  e.g.
https://id.loc.gov/authorities/names/n84804642.html
```varField.marcTag600varField.subfields.tag[a, d, t, l, 0]parent.id1371544parent.idWithCheckDigitb13715446parent.recordTypebibsposition5varField.fieldTagdvarField.ind11varField.ind20varField.subfields.content[Maimonides, Moses,, 1135-1204., Fī tadbīr al-ṣiḥḥah., German, n 84804642]_idbibs-1371544-5_indexsierra_varfields_score0```
