### ISSUE TITLE
Why didn't these METS items get through the pipeline?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/catalogue-pipeline#2366]
Quoting Ashley in platform-feedback:

> No rush on this but I have three items that aren't showing up in the Catalogue API for IIIF Builder to put online and I'm not sure why. They're unsuppressed in Sierra: b22006771, b30457701, b30547659

**Comment by alexwlchan** [comment]
b22006771 – we have picked up the unsuppressed record, why isn't it in the pipeline?

**Comment by pollecuttn** [comment]
[Passed to Ashley & Branwen to look at the graphs](https://wellcome.slack.com/archives/C8X9YKM5X/p1685517044037359?thread_ts=1684935444.911369&cid=C8X9YKM5X)

**Comment by aray-wellcome** [comment]
All sorted now, thanks!

**Comment by alexwlchan** [comment]
Super, thanks!
