### ISSUE TITLE
Hide notes that point to digitised files from Codebreakers

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/catalogue-pipeline#2432]
These notes are at best confusing and at worst wrong. We don't want to entirely remove them from the Sierra data, but nor do we want to display them on wc.org/works for now.

See https://wellcome.slack.com/archives/C8X9YKM5X/p1629900086107000

**Comment by paul-butcher** [comment]
Here is an example of one that still shows the forbidden phrase: https://wellcomecollection.org/works/a26dt8ex

Interestingly, this record does not show the forbidden phrase: https://wellcomecollection.org/works/tb8dtsev even though it is present in the corresponding Sierra data (wdkr76jt, b32723933).  I suspect something is happening in the Merge that drops all but the first note, as this has two terms-of-use notes and one location-of-duplicates note in works-identified, but only the one appears on the website.
