### ISSUE TITLE
Investigate merger faults

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/catalogue-pipeline#2512]
[See Slack thread](https://wellcome.slack.com/archives/CQ720BG02/p1704805880238569)

We got errors in the alerts channel regarding item requesting. Users seemed to be requesting items that had a double and might be a merging error. Paul has investigated, found items on the DLQ and redrove them. Two items were still displaying on the website, so it's believed further investigation is needed in ensuring the merging functions well.

**Comment by rcantin-w** [comment]
Got the error again on item 1961701 on Jan 11, 2024 @ 13:30:14.316

**Comment by paul-butcher** [comment]
It looks like this is correct now.  https://wellcomecollection.org/works/n8c9tjg7 redirects to https://wellcomecollection.org/works/mgys4kqa as expected.  I suspect that something ephemeral went awry and a message was dropped.
