### ISSUE TITLE
Missing item records

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/catalogue-pipeline#2536]
There are six records where

> Sierra suggests that item records should be visible online but they're not (although linked bib records are - work IDs listed in the csv), and this seems to be somehow connected to the 962 field in Sierra

[Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1706107574100929)

**Comment by paul-butcher** [comment]
In the original message, two records (`EPB/A/57329.v1, i12614166` and `EPB/A/57329.v2,  i12614178`) are stated as being completely absent, both corresponding to b12666579, which is szjj6gqy, which redirects to https://wellcomecollection.org/works/jb4kp3td

**Comment by paul-butcher** [comment]
szjj6gqy has a relatively large matcher graph, including b33013950 and L0005170, which are suppressed.  Could this be related to https://github.com/wellcomecollection/catalogue-pipeline/issues/1561?

**Comment by paul-butcher** [comment]
The first one on the list - mkmgxzfz has nothing else in the graph.  It's just L0025074, so it's not likely to be a merger-based problem.

**Comment by paul-butcher** [comment]
```
11:15:54.958 [main-actor-system-akka.actor.default-dispatcher-11] ERROR w.p.t.sierra.SierraTransformer - Failed to perform transform to unified item of Work[sierra-system-number/b12695567]

```

**Comment by paul-butcher** [comment]
Suspicion confirmed (for this one at least):
In [b12695567](https://catalogue.wellcomelibrary.org/search~S12?/Yb12695567&searchscope=12&SORT=D/Yb12695567&searchscope=12&SORT=D&SUBKEY=b12695567/1%2C1%2C1%2CB/marc&FF=Yb12695567&searchscope=12&SORT=DZ&1%2C1%2C), there is a [MARC 650](https://www.loc.gov/marc/bibliographic/bd650.html) field with a second indicator value of 0 (i.e. LCSH), which contains a MeSH code (D009524).

> 650  0 Press.|0sh 85106500 
> 650  0 Newspapers|xEnglish.|0D009524. 
> 650  2 Journalism|xhistory.|0D020452Q000266 
> 651  0 Great Britain.|0n  79023147 

This causes the transformer to fail because it cannot work out which kind of Library of Congress Identifier D009524 is (because it isn't one).

**Comment by paul-butcher** [comment]
This is only a problem for b12695567.  The other b numbers do not bear such an identifier/scheme mismatch.

* b32950974: ¿Both 650 fields look fine?
* b1456029x: ¿No 6xx fields?
* b12666579: ¿Both 650 and 655 look fine, must be something else?

**Comment by paul-butcher** [comment]
b12666579 is mentioned in four records out of the id minter:  szjj6gqy, hqj4zaem, qjxnq9es, xwtagnu3.  These all redirect to https://wellcomecollection.org/works/jb4kp3td

**Comment by paul-butcher** [comment]
[gcpqm6nf.pdf](https://github.com/wellcomecollection/catalogue-pipeline/files/14084681/gcpqm6nf.pdf)
[wpznxk63.pdf](https://github.com/wellcomecollection/catalogue-pipeline/files/14084683/wpznxk63.pdf)

**Comment by paul-butcher** [comment]
Before merging, xwtagnu3 has two items
```
      "items": [
        {
          "id": {
            "canonicalId": "ck5zktvq",
            "sourceIdentifier": {
              "identifierType": {
                "id": "sierra-system-number"
              },
              "ontologyType": "Item",
              "value": "i12614166"
            },
            "otherIdentifiers": [
              {
                "identifierType": {
                  "id": "sierra-identifier"
                },
                "ontologyType": "Item",
                "value": "1261416"
              }
            ],
            "type": "Identified"
          },
          "title": "Vol. 1",
          "locations": [
            {
              "locationType": {
                "id": "closed-stores"
              },
              "label": "Closed stores",
              "shelfmark": "EPB/A/57329.v1",
              "accessConditions": [
                {
                  "method": {
                    "type": "OnlineRequest"
                  },
                  "status": {
                    "type": "Open"
                  }
                }
              ],
              "type": "PhysicalLocation"
            }
          ]
        },
        {
          "id": {
            "canonicalId": "b6v5kccp",
            "sourceIdentifier": {
              "identifierType": {
                "id": "sierra-system-number"
              },
              "ontologyType": "Item",
              "value": "i12614178"
            },
            "otherIdentifiers": [
              {
                "identifierType": {
                  "id": "sierra-identifier"
                },
                "ontologyType": "Item",
                "value": "1261417"
              }
            ],
            "type": "Identified"
          },
          "title": "Vol. 2",
          "locations": [
            {
              "locationType": {
                "id": "closed-stores"
              },
              "label": "Closed stores",
              "shelfmark": "EPB/A/57329.v2",
              "accessConditions": [
                {
                  "method": {
                    "type": "OnlineRequest"
                  },
                  "status": {
                    "type": "Open"
                  }
                }
              ],
              "type": "PhysicalLocation"
            }
          ]
        }
      ],
```

jb4kp3td has one

```
      "items": [
        {
          "id": {
            "canonicalId": "fjy67ayz",
            "sourceIdentifier": {
              "identifierType": {
                "id": "sierra-system-number"
              },
              "ontologyType": "Item",
              "value": "i12020114"
            },
            "otherIdentifiers": [
              {
                "identifierType": {
                  "id": "sierra-identifier"
                },
                "ontologyType": "Item",
                "value": "1202011"
              }
            ],
            "type": "Identified"
          },
          "locations": [
            {
              "locationType": {
                "id": "closed-stores"
              },
              "label": "Closed stores",
              "accessConditions": [
                {
                  "method": {
                    "type": "OnlineRequest"
                  },
                  "status": {
                    "type": "Open"
                  }
                }
              ],
              "type": "PhysicalLocation"
            }
          ]
        }
      ],
```
After the merge, jb4kp3td has none.

**Comment by paul-butcher** [comment]
The [relevant merge rules all chain with orElse](https://github.com/wellcomecollection/catalogue-pipeline/blob/acd54e03e13d21da2066d1fd0b3dd7ea28e5b6b7/pipeline/merger/src/main/scala/weco/pipeline/merger/rules/ItemsRule.scala#L30-L37), finishing with just returning the target's item list.  This means that one of the earlier rules is being applied, returning Nil.

**Comment by paul-butcher** [comment]
Yes.  It looks like the culprit is mergeDigitalIntoPhysicalSierraTarget.

jb4kp3td has a single physical item, which means that it [merges the list of digitised items with the target's list](https://github.com/wellcomecollection/catalogue-pipeline/blob/acd54e03e13d21da2066d1fd0b3dd7ea28e5b6b7/pipeline/merger/src/main/scala/weco/pipeline/merger/rules/ItemsRule.scala#L190).  However, that [only happens if the source is a  "physical/digitised Sierra work"](https://github.com/wellcomecollection/catalogue-pipeline/blob/97e4a43ad57b26d7e933c1f2708716a46eedd3ff/pipeline/merger/src/main/scala/weco/pipeline/merger/models/Sources.scala#L32-L58)

**Comment by paul-butcher** [comment]
So, I think there are two things at play here:
1. I suspect that emptying out the list of physical locations when it can't find a linked digitised item is incorrect, and it should probably just return the target's items.
2. I think it is related to https://github.com/wellcomecollection/catalogue-pipeline/issues/1561. All four of those Sierras in the jb4kp3td graph have the same target precedence (they are all Sierras with at least one Physical item), but only xwtagnu3 has two items. The others have one.

**Comment by paul-butcher** [comment]
There is only a test for the positive side of this - i.e. Does it add Digital items to a Physical one? and not the rest of the possible scenarios - Does it combine Physical ones, what does it do if there are no digital ones?  I suspect that's a bit of an oversight.

https://github.com/wellcomecollection/catalogue-pipeline/blob/43a792fcffbae136c7595faab67166d0bc0d60b4/pipeline/merger/src/test/scala/weco/pipeline/merger/rules/ItemsRuleTest.scala#L100

**Comment by paul-butcher** [comment]
It looks like the same thing is happening for f55dwbyz and wpznxk63.  wpznxk63 has one item, f55dwbyz has three.  Everything gets merged into wpznxk63, emptying wpznxk63's item list because none of f55dwbyz's items are of the right kind.

Both ps2phs5n and f55dwbyz have one item each, but neither of them are of the right kind to merge into the other.

**Comment by paul-butcher** [comment]
It gets weirder! Why does b11675676 link to M0011992?  I can't see it in the MARC.

**Comment by paul-butcher** [comment]
[Slack ramble](https://wellcome.slack.com/archives/C02ANCYL90E/p1706620826628199)

**Comment by paul-butcher** [comment]
I've got to the bottom of this, and there are a few different problems. 

The simplest one is this:

### MeSH IDs marked as LCSH

[mkmgxzfz](https://wellcomecollection.org/works/mkmgxzfz) comes from the Miro record only, so the items are missing.  Sierra [b12695567](https://catalogue.wellcomelibrary.org/search~S12/,?SEARCH=b1269556&searchscope=12&submit.x=0&submit.y=0) is failing in the transform because it has a MeSH id in a field that should be a LoC id  `650 0 Newspapers|xEnglish.|0D009524`   There are a few of these scattered around Sierra.  It looks like something happened in August last year that set the second indicator on some fields to 0 when they had previously been 2 ([b30489313](https://catalogue.wellcomelibrary.org/record=b3048931~S12) also has an example of this happening `651  2 Latin America.|0D007843`), unfortunately, there was something [wrong with reporting around then](https://github.com/wellcomecollection/catalogue-pipeline/issues/2541), so I can't easily create a handy list of them.

The next two are related to the merging of records:

### Dropping items
We had a specific scenario in which items were simply dropped.  I'm fixing this now.

### Suspicious merges

Finally (I don't know whether this is related to the [boundwith problem](https://wellcome.slack.com/archives/C8X9YKM5X/p1704990726134399?thread_ts=1704283279.371269&cid=C8X9YKM5X) mentioned in the other thread?) There are some merges happening via links to Miro images that seem suspicious.  I'm not sure if this is something that needs to be fixed in the source data, of if it's something I can deal with in the merger.

[wpznxk63](https://wellcomecollection.org/works/wpznxk63) is the result of merging these two Sierra records with the corresponding Miro records
[b1456029x](https://catalogue.wellcomelibrary.org/search~S12?/.b1456029/.b1456029/1%2C1%2C1%2CB/marc~b1456029) (i13863034) merges with 9 Miro images, including L0013383, 
`962    000:000:URL:b0000000:000000:0:0:0:0:0:0|vn|uhttp://
       wellcomeimages.org/indexplus/image/L0013383.html|ehttp://
       wellcomeimages.org/ixbin/imageserv?MIRO=L0013383 `
[b15260963](https://catalogue.wellcomelibrary.org/search~S12?/.b1526096/.b1526096/1%2C1%2C1%2CB/marc~b1526096) (i14614224, i15122633, i15122645) also merges with L0013383. 
`089 00 L 13383 `


Something similar is happening with [jb4kp3td](https://wellcomecollection.org/works/jb4kp3td) (b1180232, b12666579, b11802339, b11802315), where there is a mixture of 089 and 962 fields linking to Miro.

Which items do we expect to see on the resulting record on the website?  Do we actually expect these two records to merge?

**Comment by amme2** [comment]
Thanks @paul-butcher.

We've sorted out the **subject headings IDs** in [mkmgxzfz](https://wellcomecollection.org/works/mkmgxzfz) and the relevant item records are now appearing online. It does look like there's a wider issue here connected to the automated subject authority control process back in August 2023, so Collections Information will pick this up and investigate further.

Similarly the **suspicious merges** examples are probably best fixed at source rather than in the merger, but that decision is based on there only being 3 examples. Are you able to check whether there are only 3? If it turns out there are thousands of examples of this issue, we might want to take a different tack in resolving it...

**Comment by paul-butcher** [comment]
I don't think we have an efficient way to find matcher relationships by that criterion. If you can fix these three for now, and we can have a think about how we can report this in the future.
