### ISSUE TITLE
Create a lambda to act as an EBSCO adapter.

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/catalogue-pipeline#2552]
As a first step towards receiving e-journal data directly from EBSCO rather than via Sierra we should set up a lambda to read from an 
 SFTP endpoint to receive MARCXML.

We will receive data from the [HLM Marc Update service](https://connect.ebsco.com/s/article/HLM-MARC-Updates-service?language=en_US), which delivers MARCXML via SFTP. We should read from the SFTP endpoint provided by EBSCO.

Part of https://github.com/wellcomecollection/platform-infrastructure/issues/426

**Comment by pollecuttn** [comment]
Planning 28/2/24: Setup a lambda to receive data from the EBSCO SFTP
