### ISSUE TITLE
Matcher graphs from the catalogue index

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/catalogue-pipeline#2557]
The script we have for matcher graphs creates them by peeking into the DynamoDB "graph store" in the pipeline - in order to expose these graphs better, we should be able to do it just using the catalogue index

**Comment by paul-butcher** [comment]
When reindexing for this, be aware of [this "short-term fix"](https://github.com/wellcomecollection/catalogue-pipeline/issues/2549#issuecomment-1935557125)
