### ISSUE TITLE
Link EBSCO-derived records with their Sierra-derived counterparts

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/catalogue-pipeline#2558]
When we start ingesting records directly from EBSCO into the pipeline, rather than via Sierra, we need to be able to resolve a Sierra b-number-derived canonical id to an EBSCO-derived entry.  The EBSCO entries will not be passing through Sierra, so we will need to link them on ISSN.

_Originally posted by @paul-butcher in https://github.com/wellcomecollection/catalogue-pipeline/issues/2556#issuecomment-1952487565_

This is for bookmark preservation.

e.g. When I visit https://wellcomecollection.org/works/fwx57bme, I will see the page for the American Journal of Nursing.

**Comment by paul-butcher** [comment]
If the existing EBSCO entries in Sierra are going to remain in Sierra (becoming stale/redundant when we ingest from EBSCO), then this can be handled by matcher/merger and redirects.

If not, then something slightly more radical will be required.

**Comment by paul-butcher** [comment]
Even if we do use the existing matcher/merger  to handle this, there is still some tricksiness.

IIRC, the matcher works by at least one side of a match knowing the document identifier for the other side.

I think that the field that we would need to match (ISSN) on is _an_ identifier _within_ the documents, rather than _the_ identifier for the EBSCO document.  I believe that some EBSCO documents will not have an ISSN, so we cannot simply declare that to be _the_ identifier.

Fortunately, the matcher doesn't care about documents, only ids, so if both sides match with the ISSN, then both sides can be part of the same matcher graph, without the ISSN-identified document needing to exist.

However, I think this might stall in the merger, which expects every id in the graph to resolve to a document.

**Comment by paul-butcher** [comment]
Part of https://github.com/wellcomecollection/platform-infrastructure/issues/426

**Comment by kenoir** [comment]
Closing as done.
