### ISSUE TITLE
 Set up an actual transformer for EBSCO MARC

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/catalogue-pipeline#2564]
One that can pull data from where it resides, and put Works into works-source.

This is to be done once the transformer can transform what we want based on the sample code.

**Comment by paul-butcher** [comment]
This may be an opportunity to set something up in a slightly different way, rather than copying the existing transformer infrastructure (e.g. take inspiration from the concepts pipeline).

**Comment by paul-butcher** [comment]
Part of https://github.com/wellcomecollection/platform-infrastructure/issues/426

**Comment by kenoir** [comment]
Closing as done.
