### ISSUE TITLE
Harmonise EBSCO and Sierra MatType codes

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/catalogue-pipeline#2572]
The [materialType code is found in the leader. (character 6)](https://techdocs.iii.com/sierraapi/Content/zObjects/bibObjectDescription.htm?Highlight=materialType).  However, this is not necessarily the same value as the one in Sierra which we rely on to define MaterialTypes in the API. (The Sierra documentation states: "However, this data is customizable in Sierra and each organization determines the codes and strings for their system.")

e.g.  Sierra `d` means Journal, but `d` in MARC Leader 06 https://www.loc.gov/marc/bibliographic/bdleader.html is "Manuscript notated music".  We have several values of materialType that are not in the official list on Leader.

Journals from EBSCO have `s` in this position, and monographs `m`.  

We need to map the values found here and/or in 008 to a value that corresponds with the one we use.

We may also need to do something about the label.

_Originally posted by @paul-butcher in https://github.com/wellcomecollection/catalogue-pipeline/issues/2563#issuecomment-1978470058_

**Comment by paul-butcher** [comment]
Part of https://github.com/wellcomecollection/platform-infrastructure/issues/426

**Comment by kenoir** [comment]
Closing as done.
