### ISSUE TITLE
Get DigitalLocation to appear in the catalogue API response for born digital works.

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/catalogue-pipeline#2623]
See https://github.com/wellcomecollection/wellcomecollection.org/issues/10782#issuecomment-2078971788 for examples

Without the DigitalLocation we are blocked from making born digital files available to download from works pages.

**Comment by paul-butcher** [comment]
The first part of this is that the Adapter didn't recognise the filename pattern for born-digital METS files.  This is now sorted.

However, I have now hit another problem, which resides in the way the source data is managed.

Merging is governed by the content of SDB_URL in the corresponding CALM file.   However, this does not contain the correct value in the examples I have just examined.  e.g. 

ARTCOO/A/3/1 - https://wellcomecollection.org/works/cj6wsn55 contains a mergeCandidate: 
```
{
          "id": {
            "canonicalId": "qdfbzarp",
            "sourceIdentifier": {
              "identifierType": {
                "id": "mets"
              },
              "ontologyType": "Work",
              "value": "a616510e-d194-48f6-be0c-9849c4de3be4"
            },
            "otherIdentifiers": []
          },
          "reason": "Archivematica work"
        }
```
That identifier is nowhere to be seen in the [born-digital METS](https://iiif.wellcomecollection.org/dash/Peek/XmlView/ARTCOO_A_3_1/METS.c95db0ab-6108-437d-9cf0-ce4ac9321f26.xml) (dapq8auy), meaning we cannot possibly link using this key.

That record generates a Work with this sourceIdentifier.
```
"sourceIdentifier": {
        "identifierType": {
          "id": "mets"
        },
        "ontologyType": "Work",
        "value": "c95db0ab-6108-437d-9cf0-ce4ac9321f26"
      },
      "canonicalId": "dapq8auy",
```

The trouble here is that the identifier of the Archivematica METS is _*NOT STABLE*_.  c95db0ab... is the _current_ identifier for that content (last modified March 15, 2024, 09:45:06 (UTC+00:00)), but a616510e... is the _old_ identifier for that content (from March 11, 2020, 18:19:08 (UTC+00:00) to the above date).

So, at some point, someone updated the CALM record to point to the Archivematica record ([using the SDB_URL field, as documented here](https://docs.wellcomecollection.org/archive-cataloguing/metadata-fields/superseded-fields)), and then a new version of the Archivematica record has been published, rendering that link dead.

**Comment by paul-butcher** [comment]
The same thing is happening with [nu6usm7g](https://wellcomecollection.org/works/nu6usm7g) (PP/MDM/A/5). The CALM record refers to c0f73173-cc87-448f-afa6-13919004e73c, (v1:  2021-03-15), but the current id is 5d56080d-b3bf-457a-b58f-c8db61fe3ccd (v2: 2024-03-21)

**Comment by pollecuttn** [comment]
Hi @paul-butcher is this deployed? Wondering if we might get to see the born digital files on the page behind a toggle at review this afternoon?
