### ISSUE TITLE
Finalise EBSCO work transforms

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/catalogue-pipeline#2642]
Follows: https://github.com/wellcomecollection/catalogue-pipeline/issues/2618

Work required to complete EBSCO transforms:
- Write a MARC based transformer for SierraParents
- Write a MARC based transformer for SierraProduction

Questions that need answering:

1. Should all the EBSCO records have "Electronic journals" as a type/technique in addition to the other values read from MARC field 655, or only that value, or just the one's it has now (without "Electronic journals")?
2.  Are we comfortable with the new records having so many concepts / subjects associated with them or should we be filtering this list further?

See: https://wellcome.slack.com/archives/C02ANCYL90E/p1715706505209179?thread_ts=1715700448.744559&cid=C02ANCYL90E

Answers to questions above, (1) we should write a transform using Leader/07 and 006/06 for material type, (2) we've been provided rules for for filtering subject headings that we can replicate.

**Comment by jcateswellcome** [comment]
part of [wellcomecollection/platform/#5738](https://github.com/wellcomecollection/platform/issues/5738)
