### ISSUE TITLE
Re-architect the batcher service so that it works as a Lambda

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/catalogue-pipeline#2721]
Part of https://github.com/wellcomecollection/platform/issues/5784

This is the specific task of refactoring the ECS service so that it can operate as an SQS triggered Lambda.

- [x] https://github.com/wellcomecollection/catalogue-pipeline/pull/2728
- [x] https://github.com/wellcomecollection/catalogue-pipeline/pull/2738
- [x] https://github.com/wellcomecollection/catalogue-pipeline/pull/2735

It should be preceded by [the RFC described in the linked issue](https://github.com/wellcomecollection/platform/issues/5789).

**Comment by paul-butcher** [comment]
One of the things I want us to consider is that the whole SQS-in/SNS-out business has its tentacles all through the invocation part of this application.   Ideally, we should be able to invoke it not just by Lambda (which would still be SQS), but also from a CLI by passing it a list of strings (probably on STDIN), without having to run pretend AWS services.

Throughout the whole pipeline, we have big chains of Akka stream stuff that might be better, both for readability and reuse, if we crack them apart and name them, preferably restricting the interface parts (SQS/SNS or STDIO or whatever) to the very periphery.

**Comment by pollecuttn** [comment]
@kenoir can this be closed now?

**Comment by kenoir** [comment]
> @kenoir can this be closed now?

I think this one should include the work to actually shift the batcher code over too? Cc @agnesgaroux.

**Comment by kenoir** [comment]
Closing as done.
