### ISSUE TITLE
Archives - Digital 🙅‍♀️ Born-digital archives 👍

### ISSUE THREAD

**Issue by agnesgaroux** [wellcomecollection/catalogue-pipeline#2742]
Update the material type from Archives - Digital to Born-digital archives 

PR https://github.com/wellcomecollection/catalogue-pipeline/pull/2743

https://github.com/wellcomecollection/catalogue-pipeline/blob/30d43caf86f1cdaf3f8155523b35801a609bfebc/common/internal_model/src/main/scala/weco/catalogue/internal_model/work/Format.scala#L109

https://github.com/wellcomecollection/catalogue-pipeline/blob/30d43caf86f1cdaf3f8155523b35801a609bfebc/pipeline/transformer/transformer_calm/src/main/scala/weco/pipeline/transformer/calm/transformers/CalmFormat.scala#L10

**Comment by kenoir** [comment]
This is unblocked by https://github.com/wellcomecollection/catalogue-pipeline/pull/2745
