### ISSUE TITLE
Inspect batcher_lambda_output to compare lambda / ECS output

### ISSUE THREAD

**Issue by agnesgaroux** [wellcomecollection/catalogue-pipeline#2747]
Part of https://github.com/wellcomecollection/platform/issues/5794

We should record the output of the ECS & Lambda batchers so that we can compare batch size, output parity, and timings.

See https://wellcome.slack.com/archives/C02ANCYL90E/p1730808651308179

## SNS  > Firehose > S3

We want a way to assert that the batcher_lambda outputs sensible stuff
We subscribe data streams to the batcher output topics (now one for EC2 and one for lambda), with separate S3 buckets as the destinations. The incoming messages are written to prefixes matching their `rootPath` 

### Source topic (existing)
catalogue-2024-08-15_batcher_output (DO NOT DELETE)
ARN
arn:aws:sns:eu-west-1:760097843905:catalogue-2024-08-15_batcher_output

DELETED ~~Subscription ARN
arn:aws:sns:eu-west-1:760097843905:catalogue-2024-08-15_batcher_output:924ce893-86d2-4cff-881a-6ee371a8a194~~

### Firehose stream 	
DELETED ~~PUT-S3-catalogue-2024-08-15-batcher-output
ARN
arn:aws:firehose:eu-west-1:760097843905:deliverystream/PUT-S3-catalogue-2024-08-15-batcher-output~~

### Destination bucket 
DELETED ~~catalogue-2024-08-15-batcher-output-audit
ARN
arn:aws:s3:::catalogue-2024-08-15-batcher-output-audit~~

### IAM role for topic to write to stream 
DELETED ~~2024-08-15-batcher-output-firehose-write
ARN
arn:aws:iam::760097843905:role/2024-08-15-batcher-firehose-write~~

DELETED ~~Policy attached to role above
2024-08-15-batcher-output-firehose-write-policy
AmazonSNSRole + SNS trust relationship~~

## Next steps
- Monitor `catalogue-2024-08-15-batcher-output-audit` bucket for incoming messages ✅
- Create the same set up for `catalogue-2024-11-05_batcher_output` and `catalogue-2024-11-05_batcher_lambda_output` ✅

**Comment by agnesgaroux** [comment]
## ECS service catalogue-2024-11-05

### Source topic 
catalogue-2024-11-05_batcher_output (DO NOT DELETE)
ARN
arn:aws:sns:eu-west-1:760097843905:catalogue-2024-11-05_batcher_output

Subscription ARN
arn:aws:sns:eu-west-1:760097843905:catalogue-2024-11-05_batcher_output:ab92456f-e16c-47ce-9ec6-b4114279fffd

### Destination bucket 
catalogue-2024-11-05-batcher-output-audit
ARN
arn:aws:s3:::catalogue-2024-11-05-batcher-output-audit

### Firehose stream 	
PUT-S3-catalogue-2024-11-05-batcher-output
ARN
arn:aws:firehose:eu-west-1:760097843905:deliverystream/PUT-S3-catalogue-2024-11-05-batcher-output

### IAM role for topic to write to stream 
2024-11-05-batcher-output-firehose-write
ARN
arn:aws:iam::760097843905:role/2024-11-05-batcher-output-firehose-write

Policy to attach to role above

**Comment by kenoir** [comment]
As the output was a bit inconsistent due to a malfunctioning batcher, there's a limit to what we can learn from this data. Suggest we review when we wire in the relation-embedder,
