### ISSUE TITLE
Relation-embedder ECS to lambda infra

### ISSUE THREAD

**Issue by agnesgaroux** [wellcomecollection/catalogue-pipeline#2770]
Part of https://github.com/wellcomecollection/platform/issues/5784

Naming concerns:
- As we replace services with lambdas, the term "lambda" is at risk of creeping all over our code and infra
- We do need a way to differentiate queues, topics, indices, etc... during development/deployment but eventually we'll be left with everything specifying "lambda" for, at that point and going forwards, no reason

**Comment by agnesgaroux** [comment]
One of the main concerns WRT the relation_embedder is the indices' read/write capacity:
- it reads from the merged index and writes to the denormalised index
- there is existing config to manage the input/load so as to avoid memory and ES (413: Content Too Large) errors 

We should replicate this in a `relation_embedder` lambda by limiting the queue concurrency, scroll size and index batch size

**Comment by kenoir** [comment]
Closing as done.
